modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="earth_pulsation"
version="0.0.5"
displayName="Earth pulsation"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="Github:https://github.com/Ironnoob73/"
logoFile="logo.png"
authors="Iron_noob_73, MCreator"
description='''
An in production forge mod made with MCreator.
'''

[[dependencies.earth_pulsation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




